/** tomb2.dll - Patch 4.1 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0x1330c8", Type: "Int8" },
        LevelCompleted: { Address: "0x1330b8", Type: "Int32" },
        LevelId: { Address: "0x132b58", Type: "Int32" },
        MenuSelection: { Address: "0x113f14", Type: "UInt16" },
        MenuState: { Address: "0x4fdf02", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x4f9fe0", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x3fd320", Type: "UInt32" },
        InterpolationFactor: { Address: "0x2d3418", Type: "UInt32" },
        NewGamePlus: { Address: "0x4fa606", Type: "UInt8" },
        LaraId: { Address: "0x345fc0", Type: "Int16" },
        Lara: { Address: "0x346170", Type: "Pointer" },
        LaraClimbState: { Address: "0x345fce", Type: "Int16" },
        LaraOxygen: { Address: "0x345fd6", Type: "Int16" },
        LaraCircleShadow: { Address: "0x346170", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        Rooms: { Address: "0x427360", Type: "Pointer" },
        RoomsCount: { Address: "0x3fd1b0", Type: "Int16" },
        LaraGunFlags: { Address: "0x346000", Type: "UInt16" },
        LaraGunType: { Address: "0x345fc4", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x3460b0", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x3460b8", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x3460ba", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x3460dc", Type: "Int16" },
        LaraAimingRight: { Address: "0x3460f4", Type: "Int16" },
        RoomType: { Address: "0x345fcc", Type: "Int16" },
        LaraHairLeftX: { Address: "0x37ebc0", Type: "Int32" },
        UiTextsCount: { Address: "0x1334c4", Type: "Int16" },
        UiDrawX: { Address: "0x2D337C", Type: "Int32" },
        UiDrawWidth: { Address: "0x2d3398", Type: "Int32" },
        UiDrawHeight: { Address: "0x2d3444", Type: "Int32" },
        UiResWidth: { Address: "0x2d33d0", Type: "Int32" },
        UiResHeight: { Address: "0x2d33d4", Type: "Int32" },
        CameraStableX: { Address: "0x2d33ec", Type: "Int32" },
        CameraStableY: { Address: "0x2D33FC", Type: "Int32" },
        CameraStableZ: { Address: "0x2D340C", Type: "Int32" },
        CameraX: { Address: "0x2d33ec", Type: "Int32" },
        CameraY: { Address: "0x2D33FC", Type: "Int32" },
        CameraZ: { Address: "0x2D340C", Type: "Int32" },
        CameraYaw: { Address: "0x2d336e", Type: "UInt16" },
        CameraPitch: { Address: "0x2d336c", Type: "UInt16" },
        CameraRightX: { Address: "0x2d2bc0", Type: "Int32" },
        CameraRightY: { Address: "0x2d2bc4", Type: "Int32" },
        CameraRightZ: { Address: "0x2d2bc8", Type: "Int32" },
        CameraUpX: { Address: "0x2D2BD0", Type: "Int32" },
        CameraUpY: { Address: "0x2D2BD4", Type: "Int32" },
        CameraUpZ: { Address: "0x2D2BD8", Type: "Int32" },
        CameraForwardX: { Address: "0x2D2BE0", Type: "Int32" },
        CameraForwardY: { Address: "0x2D2BE4", Type: "Int32" },
        CameraForwardZ: { Address: "0x2D2BE8", Type: "Int32" },
        CameraFov: { Address: "0x2d3410", Type: "Int32" },
        IsInGameScene: { Address: "0x1142ec", Type: "Int32" },
        VehicleId: { Address: "0x345fe8", Type: "Int16" },
        Entities: { Address: "0x4f9fc0", Type: "Pointer" },
        EntitiesCount: { Address: "0x3FD1B4", Type: "Int16" },
    },

    hooks: {
        RenderLara: { Address: "0x169e0", Params: ['pointer'], Return: 'void' },
        UpdateLaraAppearance: { Address: "0xa7d40", Params: [], Return: 'void' },
        LoadLevel: { Address: "0x244d0", Params: ['int', 'int', 'pointer', 'pointer'], Return: 'pointer' },
        InitializeLevelAI: { Address: "0x556b0", Params: [], Return: 'void' },
        SoundEffect: { Address: "0x987d0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x34df0", Params: [], Return: 'void' },
        Menu: { Address: "0x37010", Params: ['int'], Return: 'int' },
        Clone: { Address: "0xd8fa0", Params: ['pointer', 'pointer', 'uint64'], Return: 'pointer' },
        AddText: { Address: "0xae090", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0x80830", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0x816c0", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0x815c0", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        DrawHealth: { Address: "0x93860", Params: ['int'], Return: 'void' },
        RenderSkidoo: { Address: "0x6cde0", Params: ['pointer'], Return: 'void' },
        RenderBoat: { Address: "0x167e0", Params: ['pointer'], Return: 'void' },
        RoomChange: { Address: "0x3c4a0", Params: ['int', 'int'], Return: 'void' },
        GetRelYawPitch: { Address: "0x99ce0", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x7ffa0", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeH: { Address: "0x7fbe0", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeV: { Address: "0x7f820", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x49b90", Params: ['pointer'], Return: 'void' },
        DealDmg: { Address: "0x76150", Params: ['pointer', 'int', 'int'], Return: 'void' },
        AttachLaraHair: { Address: "0x7cc80", Params: ['int', 'int'], Return: 'void' },
        ProcessGrenade: { Address: "0x45310", Params: ['int16'], Return: 'void' },
        ProcessHarpoon: { Address: "0x44e70", Params: ['int16'], Return: 'void' },
        ModernGfx: { Address: "0x209c0", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        OgGfxPrep: { Address: "0x3c610", Params: ['int'], Return: 'uint64' },
        RemoveEntity: { Address: "0x3be70", Params: ['int'], Return: 'void' },
        GetEntityBox: { Address: "0x7b720", Params: ['pointer'], Return: 'pointer' },
        RecordWorldState: { Address: "0x61270", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x61b90", Params: ['int'], Return: 'void' },
        WorldStateRecordReplay: { Address: "0x79aa0", Params: [], Return: 'void' },
        CanInterpolateCamera: { Address: "0x99a10", Params: [], Return: 'int' },
    }
};
