/** tomb1.dll - Patch 4.1 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0xfd760", Type: "Int8" },
        LevelCompleted: { Address: "0xfd750", Type: "Int32" },
        LevelId: { Address: "0xe2ab8", Type: "Int32" },
        MenuSelection: { Address: "0xe2e54", Type: "UInt16" },
        MenuState: { Address: "0x4c8d62", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x4c4e00", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x3f1e74", Type: "UInt32" },
        InterpolationFactor: { Address: "0x29e290", Type: "UInt32" },
        NewGamePlus: { Address: "0x4c542a", Type: "UInt8" },
        LaraId: { Address: "0x310e80", Type: "Int16" },
        Lara: { Address: "0x311030", Type: "Pointer" },
        LaraOxygen: { Address: "0x310E96", Type: "Int16" },
        LaraCircleShadow: { Address: "0x311030", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        LaraGunFlags: { Address: "0x310ec0", Type: "UInt32" },
        LaraGunType: { Address: "0x310e82", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x310f70", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x310F78", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x310F7a", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x310F9C", Type: "Int16" },
        LaraAimingRight: { Address: "0x310FB4", Type: "Int16" },
        RoomType: { Address: "0x310e8c", Type: "Int16" },
        LaraHairLeftX: { Address: "0x349a80", Type: "Int32" },
        UiTextsCount: { Address: "0xfda2c", Type: "Int16" },
        UiDrawX: { Address: "0x29e23c", Type: "Int32" },
        UiDrawWidth: { Address: "0x29e258", Type: "Int32" },
        UiDrawHeight: { Address: "0x29e318", Type: "Int32" },
        UiResWidth: { Address: "0x29e2c4", Type: "Int32" },
        UiResHeight: { Address: "0x29e2c8", Type: "Int32" },
        CameraStableX: { Address: "0x29e240", Type: "Int32" },
        CameraStableY: { Address: "0x29E244", Type: "Int32" },
        CameraStableZ: { Address: "0x29E248", Type: "Int32" },
        CameraX: { Address: "0x29e2ec", Type: "Int32" },
        CameraY: { Address: "0x29e2fc", Type: "Int32" },
        CameraZ: { Address: "0x29E30C", Type: "Int32" },
        CameraYaw: { Address: "0x29E26E", Type: "UInt16" },
        CameraPitch: { Address: "0x29e26c", Type: "UInt16" },
        CameraRightX: { Address: "0x29e2e0", Type: "Int32" },
        CameraRightY: { Address: "0x29e2e4", Type: "Int32" },
        CameraRightZ: { Address: "0x29e2e8", Type: "Int32" },
        CameraUpX: { Address: "0x29E2F0", Type: "Int32" },
        CameraUpY: { Address: "0x29E2F4", Type: "Int32" },
        CameraUpZ: { Address: "0x29E2F8", Type: "Int32" },
        CameraForwardX: { Address: "0x29E300", Type: "Int32" },
        CameraForwardY: { Address: "0x29E304", Type: "Int32" },
        CameraForwardZ: { Address: "0x29E308", Type: "Int32" },
        CameraFov: { Address: "0x29e310", Type: "Int32" },
        IsInGameScene: { Address: "0xe2e50", Type: "Int32" },
        ProcessingEntityId: { Address: "0x3c0914", Type: "Int16" },
        Entities: { Address: "0x3f2178", Type: "Pointer" },
        EntitiesCount: { Address: "0x3c1b20", Type: "Int16" },
        Rooms: { Address: "0x3f2168", Type: "Pointer" },
        RoomsCount: { Address: "0x3f2030", Type: "Int16" },
        RngSeed: { Address: "0xf9a00", Type: "UInt32" },
        Projectiles: { Address: "0x3ebfc8", Type: "Pointer" },
        FlipMapFlags: { Address: "0x3eeb60", Type: "Block", Size: 0x14 },
        FlipMapStatus: { Address: "0x3f2160", Type: "UInt32" },
        InventoryWeaponSlots: { Address: "0xf8d20", Type: "Pointer" },
        InventoryWeaponQtys: { Address: "0xf8dd8", Type: "Int16" },
        InventoryWeaponsUnlocked: { Address: "0xe2abc", Type: "Int16" },
        InventoryItemSlots: { Address: "0xf95a0", Type: "Pointer" },
        InventoryItemQtys: { Address: "0xf8ff0", Type: "Int16" },
        InventoryItemsUnlocked: { Address: "0xfd6cc", Type: "Int16" },
        InventoryAmmoShotgun: { Address: "0x310fd8", Type: "Int32" },
        InventoryAmmoMagnums: { Address: "0x310fc8", Type: "Int32" },
        InventoryAmmoUzis: { Address: "0x310fd0", Type: "Int32" },
    },

    hooks: {
        RenderLara: { Address: "0xeeb0", Params: ['pointer'], Return: 'void' },
        UpdateLaraAppearance: { Address: "0x6f300", Params: [], Return: 'void' },
        LoadLevel: { Address: "0x16070", Params: ['int', 'pointer', 'pointer', 'pointer'], Return: 'pointer' },
        InitializeLevelAI: { Address: "0x2d1c0", Params: [], Return: 'void' },
        SoundEffect: { Address: "0x7b6c0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x19c00", Params: [], Return: 'void' },
        Menu: { Address: "0x1bcf0", Params: ['int'], Return: 'int' },
        Clone: { Address: "0xa9a30", Params: ['pointer', 'pointer', 'uint64'], Return: 'pointer' },
        AddText: { Address: "0x7e570", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0x51cc0", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0x52b50", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0x52a50", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        DrawHealth: { Address: "0x64f90", Params: ['int'], Return: 'void' },
        RoomChange: { Address: "0x1f010", Params: ['int', 'int'], Return: 'void' },
        GetRelYawPitch: { Address: "0x68e70", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x514e0", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeX: { Address: "0x51120", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeZ: { Address: "0x50d60", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x26b60", Params: ['pointer'], Return: 'void' },
        OnDamage: { Address: "0x44460", Params: ['pointer', 'int', 'int'], Return: 'void' },
        SimulateLaraHair: { Address: "0x4df40", Params: ['int', 'int'], Return: 'void' },
        RecordWorldState: { Address: "0x38780", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x38f00", Params: ['int'], Return: 'void' },
        ProcessDemo: { Address: "0x4ac00", Params: [], Return: 'void' },
        CanInterpolateCamera: { Address: "0x68ba0", Params: [], Return: 'int' },
        EntityBehaviourBreakable: { Address: "0x40d80", Params: ['int'], Return: 'void' },
        EntityBehaviourWolf: { Address: "0x49780", Params: ['int'], Return: 'void' },
        EntityBehaviourBat: { Address: "0x10e0", Params: ['int'], Return: 'void' },
        EntityBehaviourBear: { Address: "0x1410", Params: ['int'], Return: 'void' },
        EntityBehaviourRaptor: { Address: "0xBAE0", Params: ['int'], Return: 'void' },
        EntityBehaviourTrex: { Address: "0xc160", Params: ['int'], Return: 'void' },
        EntityBehaviourLarson: { Address: "0x322d0", Params: ['int'], Return: 'void' },
        EntityBehaviourLion: { Address: "0x49e80", Params: ['int'], Return: 'void' },
        EntityBehaviourPierre: { Address: "0x32e20", Params: ['int'], Return: 'void' },
        EntityBehaviourGorilla: { Address: "0x337b0", Params: ['int'], Return: 'void' },
        EntityBehaviourCrocodileWet: { Address: "0xafb0", Params: ['int', 'pointer'], Return: 'void' },
        EntityBehaviourCrocodileDry: { Address: "0xb430", Params: ['int'], Return: 'void' },
        EntityBehaviourRat1: { Address: "0x38080", Params: ['int', 'pointer'], Return: 'void' },
        EntityBehaviourRat2: { Address: "0x37bd0", Params: ['int', 'pointer'], Return: 'void' },
        EntityBehaviourMutantSpawn: { Address: "0x492d0", Params: ['int'], Return: 'void' },
        EntityBehaviourMutant: { Address: "0x46f20", Params: ['int'], Return: 'void' },
        EntityBehaviourCentaurSpawn: { Address: "0x495d0", Params: ['int'], Return: 'void' },
        EntityBehaviourCentaur: { Address: "0x469f0", Params: ['int'], Return: 'void' },
        EntityBehaviourFallingSword: { Address: "0x41f70", Params: ['int'], Return: 'void' },
        EntityBehaviourCowboy: { Address: "0x347f0", Params: ['int'], Return: 'void' },
        EntityBehaviourSkaterBoy: { Address: "0x33e00", Params: ['int'], Return: 'void' },
        EntityBehaviourKold: { Address: "0x34e50", Params: ['int'], Return: 'void' },
        EntityBehaviourNatla: { Address: "0x2f780", Params: ['int'], Return: 'void' },
        EntityBehaviourTorso: { Address: "0x2eff0", Params: ['int'], Return: 'void' },
        EntityBehaviourAtlanteanProjectile: { Address: "0x47b00", Params: ['int'], Return: 'void' },
        AdjustEntityCollision: { Address: "0x2eef0", Params: ['pointer', 'int'], Return: 'void' },
        SenseLara: { Address: "0x1b30", Params: ['pointer', 'pointer'], Return: 'void' },
        ProcessEntityAnimation: { Address: "0x8e60", Params: ['pointer'], Return: 'void' },
        ProcessLaraAnimation: { Address: "0x27f70", Params: ['pointer'], Return: 'void' },
        ShootLara: { Address: "0x31f60", Params: ['pointer', 'int', 'pointer', 'int'], Return: 'int' },
        AimProjectileAtLara: { Address: "0x48390", Params: ['pointer'], Return: 'void' },
        GetEntityBox: { Address: "0x4ca70", Params: ['pointer'], Return: 'pointer' },
        ATAN2: { Address: "0x68640", Params: ['int', 'int'], Return: 'int' },
        DestroyProjectile: { Address: "0x1f1f0", Params: ['int'], Return: 'void' },
        FlipMap: { Address: "0x4f690", Params: [], Return: 'void' },
        ProcessTriggers: { Address: "0x9ab0", Params: ['pointer', 'int'], Return: 'void' },
        DropEnemyItems: { Address: "0x32810", Params: ['pointer'], Return: 'void' },
        DrawEntityOnScreen: { Address: "0x4be50", Params: ['int', 'pointer'], Return: 'void' },
        AddItemToInventory: { Address: "0x1dd80", Params: ['int'], Return: 'int' },
        RemoveItemFromInventory: { Address: "0x1e520", Params: ['int'], Return: 'int' },
        GetAlternateId: { Address: "0x1db40", Params: ['int'], Return: 'int' },
        GetSector: { Address: "0x93d0", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        CalculateFloorHeight: { Address: "0x97e0", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CalculateCeilingHeight: { Address: "0xa6f0", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CreateImpactSparks: { Address: "0x41d90", Params: ['int', 'int', 'int', 'int'], Return: 'void' },
    }
};
