/** tomb3.dll - Patch 4.1 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0x18e69c", Type: "Int8" },
        LevelCompleted: { Address: "0x18e690", Type: "Int32" },
        LevelId: { Address: "0x18e16c", Type: "Int32" },
        MenuSelection: { Address: "0x16ad88", Type: "UInt16" },
        MenuState: { Address: "0x562022", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x55de00", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x461090", Type: "UInt32" },
        InterpolationFactor: { Address: "0x32f2a4", Type: "UInt32" },
        NewGamePlus: { Address: "0x55e6d4", Type: "UInt8" },
        LaraId: { Address: "0x3a1ec0", Type: "Int16" },
        LaraBase: { Address: "0x3a2070", Type: "UInt64" },
        LaraBehaviourFlags: { Address: "0x3A1Efc", Type: "Int8" },
        LaraClimbState: { Address: "0x3a1ece", Type: "Int16" },
        LaraOxygen: { Address: "0x3a1ed6", Type: "Int16" },
        LaraCircleShadow: { Address: "0x3a2070", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        LaraGunFlags: { Address: "0x3a1f00", Type: "UInt16" },
        LaraGunType: { Address: "0x3a1ec4", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x3a1fb0", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x3a1fb8", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x3a1fba", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x3a1fdc", Type: "Int16" },
        LaraAimingRight: { Address: "0x3a1ff4", Type: "Int16" },
        RoomType: { Address: "0x3a1ecc", Type: "Int16" },
        LaraHairLeftX: { Address: "0x3daac0", Type: "Int32" },
        UiTextsCount: { Address: "0x18ec5c", Type: "Int16" },
        UiDrawX: { Address: "0x32f298", Type: "Int32" },
        UiDrawWidth: { Address: "0x32f29c", Type: "Int32" },
        UiDrawHeight: { Address: "0x32f2e0", Type: "Int32" },
        UiResWidth: { Address: "0x32f2d0", Type: "Int32" },
        UiResHeight: { Address: "0x32f2d4", Type: "Int32" },
        CameraStableX: { Address: "0x32f30c", Type: "Int32" },
        CameraStableY: { Address: "0x32f31c", Type: "Int32" },
        CameraStableZ: { Address: "0x32f32c", Type: "Int32" },
        CameraX: { Address: "0x32eaac", Type: "Int32" },
        CameraY: { Address: "0x32eabc", Type: "Int32" },
        CameraZ: { Address: "0x32eacc", Type: "Int32" },
        CameraYaw: { Address: "0x32f28e", Type: "UInt16" },
        CameraPitch: { Address: "0x32f28c", Type: "UInt16" },
        CameraRightX: { Address: "0x32f300", Type: "Int32" },
        CameraRightY: { Address: "0x32f304", Type: "Int32" },
        CameraRightZ: { Address: "0x32f308", Type: "Int32" },
        CameraUpX: { Address: "0x32f310", Type: "Int32" },
        CameraUpY: { Address: "0x32f314", Type: "Int32" },
        CameraUpZ: { Address: "0x32f318", Type: "Int32" },
        CameraForwardX: { Address: "0x32f320", Type: "Int32" },
        CameraForwardY: { Address: "0x32f324", Type: "Int32" },
        CameraForwardZ: { Address: "0x32f328", Type: "Int32" },
        CameraFov: { Address: "0x32f2d8", Type: "Int32" },
        IsInGameScene: { Address: "0x1682dc", Type: "Int32" },
        VehicleId: { Address: "0x3a1ee8", Type: "Int16" },
        Entities: { Address: "0x48b168", Type: "Pointer" },
        EntitiesCount: { Address: "0x460310", Type: "Int16" },
        Rooms: { Address: "0x461140", Type: "Pointer" },
        RoomsCount: { Address: "0x460290", Type: "Int16" },
    },

    hooks: {
        RenderLara: { Address: "0x29c50", Params: ['pointer'], Return: 'void' },
        UpdatePhotoMode: { Address: "0xfaac0", Params: [], Return: 'void' },
        UpdateLighting: { Address: "0xd76c0", Params: ['int', 'int', 'int', 'int', 'pointer'], Return: 'void' },
        LoadLevel: { Address: "0x3b820", Params: ['int', 'int', 'pointer', 'pointer'], Return: 'pointer' },
        LaraInLevel: { Address: "0x752a0", Params: ['int'], Return: 'void' },
        SoundEffect: { Address: "0xe6410", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x48a20", Params: [], Return: 'void' },
        Menu: { Address: "0x4b510", Params: ['int'], Return: 'pointer' },
        Clone: { Address: "0x129ba0", Params: ['pointer', 'pointer', 'uint64'], Return: 'void' },
        AddText: { Address: "0xfd5b0", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0xc9710", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0xca5a0", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawHealth: { Address: "0xe2790", Params: ['int'], Return: 'void' },
        RoomChange: { Address: "0x51e80", Params: ['int', 'int'], Return: 'void' },
        RenderEntity: { Address: "0x296f0", Params: ['pointer'], Return: 'void' },
        GetRelYawPitch: { Address: "0xe7920", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0xc8e80", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeH: { Address: "0xc8ac0", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeV: { Address: "0xc8700", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x682d0", Params: ['pointer'], Return: 'void' },
        DealDmg: { Address: "0xbc460", Params: ['pointer', 'int', 'int'], Return: 'void' },
        AttachLaraHair: { Address: "0xc5830", Params: ['int', 'int'], Return: 'void' },
        ProcessGrenade: { Address: "0x631b0", Params: ['int16'], Return: 'void' },
        ProcessRocket: { Address: "0x62120", Params: ['int16'], Return: 'void' },
        ProcessHarpoon: { Address: "0x61500", Params: ['int16'], Return: 'void' },
        ModernGfx: { Address: "0x30740", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        RemoveEntity: { Address: "0x51830", Params: ['int'], Return: 'void' },
        GetEntityBox: { Address: "0xc42d0", Params: ['pointer'], Return: 'pointer' },
        RecordWorldState: { Address: "0x9c890", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x9d360", Params: ['int'], Return: 'void' },
        WorldStateRecordReplay: { Address: "0xc2630", Params: [], Return: 'void' },
        CanInterpolateCamera: { Address: "0xe7650", Params: [], Return: 'int' },
    }
};
