/** tomb5.dll - Patch 1 */
module.exports = {
    variables: {
        OutfitsLaraHairYoung: { Address: "0x1ac390", Type: "UInt64" },
        OutfitsLaraHairOld: { Address: "0x1ac3f0", Type: "UInt64" },
        OutfitsLaraSomeBasePointer: { Address: "0x6a6460", Type: "UInt64" },
        OutfitsPointer: { Address: "0x11f380", Type: "UInt64" },
        FacesPointer: { Address: "0x11f8f0", Type: "UInt64" },
        BinaryTick: { Address: "0x1ad7ec", Type: "Int8" },
        LevelChange: { Address: "0x64e1f0", Type: "Int32" },
        ReturnToMainMenu: { Address: "0x1ad794", Type: "Int8" },
        NewGamePlus: { Address: "0x6522b8", Type: "UInt8" },
        InterpolationFactor: { Address: "0x4e6388", Type: "UInt32" },
        LaraId: { Address: "0x4e5140", Type: "Int16" },
        Lara: { Address: "0x4e5300", Type: "Pointer" },
        LaraOxygen: { Address: "0x4e5156", Type: "Int16" },
        LaraPoisoned: { Address: "0x4e5172", Type: "Int16" },
        PoisonFactor: { Address: "0x1ad7bc", Type: "Int16" },
        Rooms: { Address: "0x652268", Type: "Pointer" },
        RoomsCount: { Address: "0x64e930", Type: "Int16" },
        LaraCircleShadow: { Address: "0x1a9bc0", Type: "Block", Pointer: "0x0", Size: "0xc" },
        LaraClimbState: { Address: "0x4E514E", Type: "Int16" },
        LaraBehaviourFlags: { Address: "0x4E5184", Type: "Int8" },
        LaraHairLeftX: { Address: "0x4e9600", Type: "Int32" },
        LaraHairRightX: { Address: "0x4E9CAC", Type: "Int32" },
        LaraGunFlagsLeft: { Address: "0x4e5244", Type: "Int16" },
        LaraGunFlagsRight: { Address: "0x4e525c", Type: "Int16" },
        LaraGunType: { Address: "0x4e5144", Type: "Int16" },
        LaraAimingEnemy: { Address: "0x4e5210", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x4e5218", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x4e521a", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x4e523c", Type: "Int16" },
        LaraScopeActive: { Address: "0x1ad834", Type: "Int32" },
        LaraScopeYaw: { Address: "0x4e5220", Type: "Int16" },
        LaraScopePitch: { Address: "0x4e5222", Type: "Int16" },
        LaraAimingRight: { Address: "0x4e5254", Type: "Int16" },
        RoomType: { Address: "0x4e514c", Type: "Int16" },
        UiDrawX: { Address: "0x4e6290", Type: "Int32" },
        UiDrawWidth: { Address: "0x4e6294", Type: "Int32" },
        UiDrawHeight: { Address: "0x4e62b4", Type: "Int32" },
        UiResWidth: { Address: "0x4e62d8", Type: "Int32" },
        UiResHeight: { Address: "0x4e62dc", Type: "Int32" },
        CameraStableX: { Address: "0x4e634c", Type: "Int32" },
        CameraStableY: { Address: "0x4e635c", Type: "Int32" },
        CameraStableZ: { Address: "0x4e636c", Type: "Int32" },
        CameraX: { Address: "0x1a9a70", Type: "Int32", Pointer: "0xc" },
        CameraY: { Address: "0x1a9a70", Type: "Int32", Pointer: "0x10" },
        CameraZ: { Address: "0x1a9a70", Type: "Int32", Pointer: "0x14" },
        CameraYaw: { Address: "0x4e62ae", Type: "UInt16" },
        CameraPitch: { Address: "0x4e62ac", Type: "UInt16" },
        CameraRightX: { Address: "0x4e6340", Type: "Int32" },
        CameraRightY: { Address: "0x4e6344", Type: "Int32" },
        CameraRightZ: { Address: "0x4e6348", Type: "Int32" },
        CameraUpX: { Address: "0x4e6350", Type: "Int32" },
        CameraUpY: { Address: "0x4e6354", Type: "Int32" },
        CameraUpZ: { Address: "0x4e6358", Type: "Int32" },
        CameraForwardX: { Address: "0x4e6360", Type: "Int32" },
        CameraForwardY: { Address: "0x4e6364", Type: "Int32" },
        CameraForwardZ: { Address: "0x4e6368", Type: "Int32" },
        CameraFov: { Address: "0x4e62e0", Type: "Int32" },
        Entities: { Address: "0x6607e8", Type: "Pointer" },
        EntitiesCount: { Address: "0x64e934", Type: "Int16" },
        Guns: { Address: "0x1a8f10", Type: "Int8" },
    },

    hooks: {
        RenderLara: { Address: "0x2edf0", Params: ['pointer'], Return: 'void' },
        ApplySettings: { Address: "0xe85d0", Params: ['pointer', 'pointer'], Return: 'void' },
        LoadedLevel: { Address: "0xf3740", Params: ['pointer'], Return: 'void' },
        InitializeLevelAI: { Address: "0x81c20", Params: ['int'], Return: 'void' },
        SoundEffect: { Address: "0xa0fe0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        ProcessFreeaim: { Address: "0x13350", Params: ['pointer', 'pointer', 'int', 'int'], Return: 'void' },
        DetectHit: { Address: "0x9ca80", Params: ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0xdcf70", Params: [], Return: 'void' },
        Clone: { Address: "0x113ac0", Params: ['pointer', 'pointer', 'uint64'], Return: 'void' },
        RenderText: { Address: "0xdcdb0", Params: ['int', 'int', 'int', 'pointer', 'int'], Return: 'pointer' },
        DrawSetup: { Address: "0xa2030", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0xa2b50", Params: ['float', 'float', 'float', 'float', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0xa2aa0", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        RoomChange: { Address: "0x448d0", Params: ['int', 'int'], Return: 'void' },
        RenderEntity: { Address: "0x2fcb0", Params: ['pointer'], Return: 'void' },
        GetRelYawPitch: { Address: "0x9e500", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x12d00", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeX: { Address: "0x12940", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeZ: { Address: "0x12580", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x59be0", Params: ['pointer'], Return: 'void' },
        OnDamage: { Address: "0x5a540", Params: ['pointer', 'int', 'int', 'int'], Return: 'void' },
        CreateGraphic: { Address: "0x31eb0", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        GetEntityBox: { Address: "0x990b0", Params: ['pointer'], Return: 'pointer' },
        RemoveEntity: { Address: "0x44310", Params: ['int'], Return: 'void' },
        SimulateLaraHair: { Address: "0xe55f0", Params: ['int', 'int'], Return: 'void' },
        ResetLaraHair: { Address: "0xe4df0", Params: [], Return: 'void' },
    }
};
