/** tomb1.dll - Patch 4 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0xf95b0", Type: "Int8" },
        LevelCompleted: { Address: "0xF95A0", Type: "Int32" },
        LevelId: { Address: "0xdea54", Type: "Int32" },
        MenuSelection: { Address: "0xe3f88", Type: "UInt16" },
        MenuState: { Address: "0x4c4b82", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x4c0c20", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x3edc94", Type: "UInt32" },
        InterpolationFactor: { Address: "0x29a0b0", Type: "UInt32" },
        NewGamePlus: { Address: "0x4c124a", Type: "UInt8" },
        LaraId: { Address: "0x30cca0", Type: "Int16" },
        Lara: { Address: "0x30ce50", Type: "Pointer" },
        LaraOxygen: { Address: "0x30CCB6", Type: "Int16" },
        LaraCircleShadow: { Address: "0x30ce50", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        LaraGunFlags: { Address: "0x30cce0", Type: "UInt32" },
        LaraGunType: { Address: "0x30CCA2", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x30cd90", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x30cd98", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x30CD9A", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x30CDBC", Type: "Int16" },
        LaraAimingRight: { Address: "0x30CDD4", Type: "Int16" },
        RoomType: { Address: "0x30CCAC", Type: "Int16" },
        LaraHairLeftX: { Address: "0x3458a0", Type: "Int32" },
        UiTextsCount: { Address: "0x1003E0", Type: "Int16" },
        UiDrawX: { Address: "0x29a05c", Type: "Int32" },
        UiDrawWidth: { Address: "0x29a078", Type: "Int32" },
        UiDrawHeight: { Address: "0x29a138", Type: "Int32" },
        UiResWidth: { Address: "0x29a0e4", Type: "Int32" },
        UiResHeight: { Address: "0x29a0e8", Type: "Int32" },
        CameraStableX: { Address: "0x29a080", Type: "Int32" },
        CameraStableY: { Address: "0x29a084", Type: "Int32" },
        CameraStableZ: { Address: "0x29a088", Type: "Int32" },
        CameraX: { Address: "0x29A10C", Type: "Int32" },
        CameraY: { Address: "0x29A11C", Type: "Int32" },
        CameraZ: { Address: "0x29A12C", Type: "Int32" },
        CameraYaw: { Address: "0x29a08e", Type: "UInt16" },
        CameraPitch: { Address: "0x29a08c", Type: "UInt16" },
        CameraRightX: { Address: "0x29A100", Type: "Int32" },
        CameraRightY: { Address: "0x29A104", Type: "Int32" },
        CameraRightZ: { Address: "0x29A108", Type: "Int32" },
        CameraUpX: { Address: "0x29A110", Type: "Int32" },
        CameraUpY: { Address: "0x29A114", Type: "Int32" },
        CameraUpZ: { Address: "0x29A118", Type: "Int32" },
        CameraForwardX: { Address: "0x29A120", Type: "Int32" },
        CameraForwardY: { Address: "0x29A124", Type: "Int32" },
        CameraForwardZ: { Address: "0x29A128", Type: "Int32" },
        CameraFov: { Address: "0x29A130", Type: "Int32" },
        IsInGameScene: { Address: "0xDEA78", Type: "Int32" },
        Entities: { Address: "0x3edf98", Type: "Pointer" },
        EntitiesCount: { Address: "0x3ede50", Type: "Int16" },
        Rooms: { Address: "0x3edf88", Type: "Pointer" },
        RoomsCount: { Address: "0x3EDE50", Type: "Int16" },
        ProcessingEntityId: { Address: "0x3bc734", Type: "Int16" },
        RngSeed: { Address: "0xe9938", Type: "UInt32" },
        Projectiles: { Address: "0x3e7de8", Type: "Pointer" },
        FlipMapFlags: { Address: "0x3ea980", Type: "Block", Size: 0x14 },
        FlipMapStatus: { Address: "0x3edf80", Type: "UInt32" },
        InventoryWeaponSlots: { Address: "0xf4d60", Type: "Pointer" },
        InventoryWeaponQtys: { Address: "0xf4e18", Type: "Int16" },
        InventoryWeaponsUnlocked: { Address: "0xdea7c", Type: "Int16" },
        InventoryItemSlots: { Address: "0xf5590", Type: "Pointer" },
        InventoryItemQtys: { Address: "0xf4fe0", Type: "Int16" },
        InventoryItemsUnlocked: { Address: "0xf951c", Type: "Int16" },
        InventoryAmmoShotgun: { Address: "0x30cdf8", Type: "Int32" },
        InventoryAmmoMagnums: { Address: "0x30cde8", Type: "Int32" },
        InventoryAmmoUzis: { Address: "0x30cdf0", Type: "Int32" },
    },

    hooks: {
        RenderLara: { Address: "0xee40", Params: ['pointer'], Return: 'void' },
        UpdateLaraAppearance: { Address: "0x6ca50", Params: [], Return: 'void' },
        LoadLevel: { Address: "0x15ea0", Params: ['int', 'pointer', 'pointer', 'pointer'], Return: 'pointer' },
        InitializeLevelAI: { Address: "0x2cac0", Params: [], Return: 'void' },
        SoundEffect: { Address: "0x78ff0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x19780", Params: [], Return: 'void' },
        Menu: { Address: "0x1b850", Params: ['int'], Return: 'int' },
        Clone: { Address: "0x8e780", Params: ['pointer', 'pointer', 'uint64'], Return: 'pointer' },
        AddText: { Address: "0x7be50", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0x50460", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0x51320", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0x51220", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        DrawHealth: { Address: "0x62740", Params: ['int'], Return: 'void' },
        RoomChange: { Address: "0x1eab0", Params: ['int', 'int'], Return: 'void' },
        CalculateYawPitch: { Address: "0x664c0", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        TraceLineOfSight: { Address: "0x4fcc0", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeX: { Address: "0x4f900", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeZ: { Address: "0x4f540", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x26520", Params: ['pointer'], Return: 'void' },
        OnDamage: { Address: "0x436e0", Params: ['pointer', 'int', 'int'], Return: 'void' },
        SimulateLaraHair: { Address: "0x4c8c0", Params: ['int', 'int'], Return: 'void' },
        RecordWorldState: { Address: "0x37ef0", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x38670", Params: ['int'], Return: 'void' },
        ProcessDemo: { Address: "0x49d50", Params: [], Return: 'void' },
        GetSector: { Address: "0x9470", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        CalculateFloorHeight: { Address: "0x9880", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CalculateCeilingHeight: { Address: "0xa7b0", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CanInterpolateCamera: { Address: "0x66200", Params: [], Return: 'int' },
        AddItemToInventory: { Address: "0x1dd50", Params: ['int'], Return: 'int' },
        RemoveItemFromInventory: { Address: "0x1dfc0", Params: ['int'], Return: 'int' },
        FlipMap: { Address: "0x4ddc0", Params: [], Return: 'void' },
        GetAlternateId: { Address: "0x1d5f0", Params: ['int'], Return: 'int' },
        Atan2: { Address: "0x65c90", Params: ['int', 'int'], Return: 'int' },
        DestroyProjectile: { Address: "0x1eca0", Params: ['int'], Return: 'void' },
        ProcessTriggers: { Address: "0x9b60", Params: ['pointer', 'int'], Return: 'void' },
        ProcessLaraAnimation: { Address: "0x27920", Params: ['pointer'], Return: 'void' },
        DropEnemyItems: { Address: "0x32230", Params: ['pointer'], Return: 'void' },
        DrawEntityOnScreen: { Address: "0x4afd0", Params: ['int', 'pointer'], Return: 'void' },
        CreateBloodSplatter: { Address: "0x12d90", Params: ['int', 'int', 'int', 'uint16', 'int16', 'int16'], Return: 'int' },
        CreateImpactSparks: { Address: "0x41000", Params: ['int', 'int', 'int', 'int'], Return: 'void' },
        ShootLara: { Address: "0x31970", Params: ['pointer', 'int', 'pointer', 'int'], Return: 'int' },
        GetBonePosition: { Address: "0x4b9f0", Params: ['pointer', 'pointer', 'int'], Return: 'void' },
        AdjustEntityCollision: { Address: "0x2e820", Params: ['pointer', 'int'], Return: 'void' },
        SenseLara: { Address: "0x1bb0", Params: ['pointer', 'pointer'], Return: 'void' },
        UpdateEnemyMood: { Address: "0x22f0", Params: ['pointer', 'pointer', 'int'], Return: 'void' },
        ProcessEntityAnimation: { Address: "0x8ef0", Params: ['pointer'], Return: 'void' },
        ProcessEntityMovement: { Address: "0x2eb0", Params: ['int', 'int', 'int'], Return: 'int' },
        AimProjectileAtLara: { Address: "0x474a0", Params: ['pointer'], Return: 'void' },
        ShootAtlanteanMeatball: { Address: "0x47670", Params: ['int', 'int', 'int', 'int64', 'uint16', 'int16', 'uint16'], Return: 'void' },
        ShootAtlanteanBullet: { Address: "0x475d0", Params: ['int', 'int', 'int', 'int64', 'uint16', 'int16', 'uint16'], Return: 'void' },
        GetEntityBox: { Address: "0x4bbf0", Params: ['pointer'], Return: 'pointer' },
        EntityWolf: { Address: "0x488a0", Params: ['int'], Return: 'void' },
        EntityBat: { Address: "0x10f0", Params: ['int'], Return: 'void' },
        EntityBear: { Address: "0x1420", Params: ['int'], Return: 'void' },
        EntityRaptor: { Address: "0xbbc0", Params: ['int'], Return: 'void' },
        EntityTrex: { Address: "0xc260", Params: ['int'], Return: 'void' },
        EntityGorilla: { Address: "0x32eb0", Params: ['int'], Return: 'void' },
        EntityCrocodileDry: { Address: "0xb080", Params: ['int', 'pointer'], Return: 'void' },
        EntityCrocodileWet: { Address: "0xb500", Params: ['int'], Return: 'void' },
        EntityRatDry: { Address: "0x37830", Params: ['int', 'pointer'], Return: 'void' },
        EntityRatWet: { Address: "0x37360", Params: ['int', 'pointer'], Return: 'void' },
        EntityLarson: { Address: "0x31ce0", Params: ['int'], Return: 'void' },
        EntityPierre: { Address: "0x32520", Params: ['int'], Return: 'void' },
        EntityCowboy: { Address: "0x33f10", Params: ['int'], Return: 'void' },
        EntitySkaterBoy: { Address: "0x33510", Params: ['int'], Return: 'void' },
        EntityKold: { Address: "0x34570", Params: ['int'], Return: 'void' },
        EntityMutant: { Address: "0x46050", Params: ['int'], Return: 'void' },
        EntityMutantSpawn: { Address: "0x483e0", Params: ['int'], Return: 'void' },
        EntityCentaur: { Address: "0x45b20", Params: ['int'], Return: 'void' },
        EntityCentaurSpawn: { Address: "0x486f0", Params: ['int'], Return: 'void' },
        EntityNatla: { Address: "0x2f0c0", Params: ['int'], Return: 'void' },
        EntityTorso: { Address: "0x2e930", Params: ['int'], Return: 'void' },
        EntityCat: { Address: "0x48fa0", Params: ['int'], Return: 'void' },
        EntityFallingSword: { Address: "0x411f0", Params: ['int'], Return: 'void' },
        EntityAtlanteanProjectile: { Address: "0x46c10", Params: ['int'], Return: 'void' },
        EntityBarricade: { Address: "0x30bd0", Params: ['int'], Return: 'void' },
        EntityBoulder: { Address: "0x3f200", Params: ['int'], Return: 'void' },
        EntityBreakable: { Address: "0x40230", Params: ['int'], Return: 'void' },
        EntityDartEmitter: { Address: "0x418b0", Params: ['int'], Return: 'void' },
        EntityDoor: { Address: "0x30620", Params: ['int'], Return: 'void' },
        EntityFallingCeiling: { Address: "0x40d70", Params: ['int'], Return: 'void' },
        EntityLavaFlow: { Address: "0x431e0", Params: ['int'], Return: 'void' },
        EntityLightningBall: { Address: "0x2afb0", Params: ['int'], Return: 'void' },
        EntityMovingBlock: { Address: "0x2e6f0", Params: ['int'], Return: 'void' },
        EntityPushBlock: { Address: "0x2dae0", Params: ['int'], Return: 'void' },
        EntitySuspendedShack: { Address: "0x30c90", Params: ['int'], Return: 'void' },
        EntitySwingBlade: { Address: "0x3ffd0", Params: ['int'], Return: 'void' },
        EntityThorHammerHandle: { Address: "0x2c4d0", Params: ['int'], Return: 'void' },
        EntityTrapDoor: { Address: "0x3fdc0", Params: ['int'], Return: 'void' },
        EntitySwitch: { Address: "0x36a70", Params: ['int'], Return: 'void' },
    }
};
