/** tomb1.dll - Patch 4 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0xf95b0", Type: "Int8" },
        LevelCompleted: { Address: "0xF95A0", Type: "Int32" },
        LevelId: { Address: "0xdea54", Type: "Int32" },
        MenuSelection: { Address: "0xe3f88", Type: "UInt16" },
        MenuState: { Address: "0x4c4b82", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x4c0c20", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x3edc94", Type: "UInt32" },
        InterpolationFactor: { Address: "0x29a0b0", Type: "UInt32" },
        NewGamePlus: { Address: "0x4c124a", Type: "UInt8" },
        LaraId: { Address: "0x30cca0", Type: "Int16" },
        LaraBase: { Address: "0x30ce50", Type: "Int64" },
        LaraOxygen: { Address: "0x30CCB6", Type: "Int16" },
        LaraCircleShadow: { Address: "0x30ce50", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        LaraBasicData: { Address: "0x30ce50", Type: "Block", Pointer: "0x0", Size: "0x28" },
        LaraGunFlags: { Address: "0x30cce0", Type: "UInt32" },
        LaraGunType: { Address: "0x30CCA2", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x30cd90", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x30cd98", Type: "Int16" },
        LaraAimingPitch: { Address: "0x30CD9A", Type: "Int16" },
        LaraAimingLeft: { Address: "0x30CDBC", Type: "Int16" },
        LaraAimingRight: { Address: "0x30CDD4", Type: "Int16" },
        RoomType: { Address: "0x30CCAC", Type: "Int16" },
        LaraHairLeftX: { Address: "0x3458a0", Type: "Int32" },
        UiTextsCount: { Address: "0x1003E0", Type: "Int16" },
        UiDrawX: { Address: "0x29a05c", Type: "Int32" },
        UiDrawWidth: { Address: "0x29a078", Type: "Int32" },
        UiDrawHeight: { Address: "0x29a138", Type: "Int32" },
        UiResWidth: { Address: "0x29a0e4", Type: "Int32" },
        UiResHeight: { Address: "0x29a0e8", Type: "Int32" },
        CameraFixedX: { Address: "0x29a080", Type: "Int32" },
        CameraFixedY: { Address: "0x29a084", Type: "Int32" },
        CameraFixedZ: { Address: "0x29a088", Type: "Int32" },
        CameraX: { Address: "0x29A10C", Type: "Int32" },
        CameraY: { Address: "0x29A11C", Type: "Int32" },
        CameraZ: { Address: "0x29A12C", Type: "Int32" },
        CameraYaw: { Address: "0x29a08e", Type: "UInt16" },
        CameraPitch: { Address: "0x29a08c", Type: "UInt16" },
        CameraRightX: { Address: "0x29A100", Type: "Int32" },
        CameraUpX: { Address: "0x29A110", Type: "Int32" },
        CameraForwardX: { Address: "0x29A120", Type: "Int32" },
        CameraFov: { Address: "0x29A130", Type: "Int32" },
        IsInGameScene: { Address: "0xDEA78", Type: "Int32" },
        Entities: { Address: "0x3edf98", Type: "Pointer" },
        EntitiesCount: { Address: "0x3ede50", Type: "Int16" },
        Rooms: { Address: "0x3edf88", Type: "Pointer" },
        RoomsCount: { Address: "0x3EDE50", Type: "Int16" },
        OgModelsOffset: "0x3edc88",
        OgModelsWeaponOffset2: "0x3ef1b2",
        OgModelsWeaponOffset: "0x3edfc2",
        OgModelsAngwyOffset: "0x3F03A2",
        OgModelsFace: "0x30cd78",
        OgModelsLeftHand: "0x30cd70",
        OgModelsRightHand: "0x30cd58",
        OgModelsLeftPocket: "0x30cd10",
        OgModelsRightPocket: "0x30cd28",
        OgModelsBackPocket: "0x30cd40"
    },

    hooks: {
        RenderLara: { Address: "0xee40", Params: ['pointer'], Return: 'void' },
        UpdatePhotoMode: { Address: "0x6ca50", Params: [], Return: 'void' },
        LoadLevel: { Address: "0x15ea0", Params: ['int', 'pointer', 'pointer', 'pointer'], Return: 'pointer' },
        LaraInLevel: { Address: "0x2cac0", Params: [], Return: 'void' },
        SoundEffect: { Address: "0x78ff0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x19780", Params: [], Return: 'void' },
        Menu: { Address: "0x1b850", Params: ['int'], Return: 'pointer' },
        Clone: { Address: "0x8e780", Params: ['pointer', 'pointer', 'uint64'], Return: 'void' },
        AddText: { Address: "0x7be50", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0x50460", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0x51320", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawHealth: { Address: "0x62740", Params: ['int'], Return: 'void' },
        RoomChange: { Address: "0x1eab0", Params: ['int', 'int'], Return: 'void' },
        GetRelYawPitch: { Address: "0x664c0", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x4fcc0", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeH: { Address: "0x4f900", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeV: { Address: "0x4f540", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x26520", Params: ['pointer'], Return: 'void' },
        DealDmg: { Address: "0x436e0", Params: ['pointer', 'int', 'int'], Return: 'void' },
        AttachLaraHair: { Address: "0x4c8c0", Params: ['int', 'int'], Return: 'void' },
        RecordWorldState: { Address: "0x37ef0", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x38670", Params: ['int'], Return: 'void' },
        WorldStateRecordReplay: { Address: "0x49d50", Params: [], Return: 'void' },
        CanInterpolateCamera: { Address: "0x66200", Params: [], Return: 'int' },
    }
};
