/** tomb2.dll - Patch 4 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0x12ff54", Type: "Int8" },
        LevelCompleted: { Address: "0x12FF40", Type: "Int32" },
        LevelId: { Address: "0x12f9e8", Type: "Int32" },
        MenuSelection: { Address: "0x110fd4", Type: "UInt16" },
        MenuState: { Address: "0x4fad62", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x4f6e40", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x3fa180", Type: "UInt32" },
        InterpolationFactor: { Address: "0x2cfa98", Type: "UInt32" },
        NewGamePlus: { Address: "0x4f7466", Type: "UInt8" },
        LaraId: { Address: "0x30eaa0", Type: "Int16" },
        Lara: { Address: "0x342fc0", Type: "Pointer" },
        LaraOxygen: { Address: "0x30EAB6", Type: "Int16" },
        LaraCircleShadow: { Address: "0x342fc0", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        LaraClimbState: { Address: "0x30EAAe", Type: "Int16" },
        LaraGunFlags: { Address: "0x30eae0", Type: "UInt16" },
        LaraGunType: { Address: "0x30EAA4", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x30eb90", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x30eb98", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x30eb9a", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x30ebbc", Type: "Int16" },
        LaraAimingRight: { Address: "0x30ebd4", Type: "Int16" },
        RoomType: { Address: "0x30EAAC", Type: "Int16" },
        LaraHairLeftX: { Address: "0x37ba20", Type: "Int32" },
        UiTextsCount: { Address: "0x130B34", Type: "Int16" },
        UiDrawX: { Address: "0x2cf9ec", Type: "Int32" },
        UiDrawWidth: { Address: "0x2CFA18", Type: "Int32" },
        UiDrawHeight: { Address: "0x2CFAc4", Type: "Int32" },
        UiResWidth: { Address: "0x2CFA50", Type: "Int32" },
        UiResHeight: { Address: "0x2CFA54", Type: "Int32" },
        CameraStableX: { Address: "0x2cfa6c", Type: "Int32" },
        CameraStableY: { Address: "0x2cfa7c", Type: "Int32" },
        CameraStableZ: { Address: "0x2cfa8c", Type: "Int32" },
        CameraX: { Address: "0x2cfa6c", Type: "Int32" },
        CameraY: { Address: "0x2cfa7c", Type: "Int32" },
        CameraZ: { Address: "0x2cfa8c", Type: "Int32" },
        CameraYaw: { Address: "0x2CFA0E", Type: "UInt16" },
        CameraPitch: { Address: "0x2CFA0C", Type: "UInt16" },
        CameraRightX: { Address: "0x2cfae0", Type: "Int32" },
        CameraRightY: { Address: "0x2cfae4", Type: "Int32" },
        CameraRightZ: { Address: "0x2cfae8", Type: "Int32" },
        CameraUpX: { Address: "0x2CFAF0", Type: "Int32" },
        CameraUpY: { Address: "0x2CFAF4", Type: "Int32" },
        CameraUpZ: { Address: "0x2CFAF8", Type: "Int32" },
        CameraForwardX: { Address: "0x2CFB00", Type: "Int32" },
        CameraForwardY: { Address: "0x2CFB04", Type: "Int32" },
        CameraForwardZ: { Address: "0x2CFB08", Type: "Int32" },
        CameraFov: { Address: "0x2CFA90", Type: "Int32" },
        IsInGameScene: { Address: "0x110E9C", Type: "Int32" },
        VehicleId: { Address: "0x30EAC8", Type: "Int16" },
        Entities: { Address: "0x4f6e20", Type: "Pointer" },
        EntitiesCount: { Address: "0x3fa010", Type: "Int16" },
        Rooms: { Address: "0x4241c0", Type: "Pointer" },
        RoomsCount: { Address: "0x3FA010", Type: "Int16" },
    },

    hooks: {
        RenderLara: { Address: "0x16b30", Params: ['pointer'], Return: 'void' },
        UpdateLaraAppearance: { Address: "0xa6300", Params: [], Return: 'void' },
        LoadLevel: { Address: "0x24210", Params: ['int', 'int', 'pointer', 'pointer'], Return: 'pointer' },
        InitializeLevelAI: { Address: "0x559b0", Params: [], Return: 'void' },
        SoundEffect: { Address: "0x96e30", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x35360", Params: [], Return: 'void' },
        Menu: { Address: "0x37580", Params: ['int'], Return: 'int' },
        Clone: { Address: "0xbe9e0", Params: ['pointer', 'pointer', 'uint64'], Return: 'pointer' },
        AddText: { Address: "0xac5c0", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0x7ffd0", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0x80e90", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0x80d90", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        DrawHealth: { Address: "0x92020", Params: ['int'], Return: 'void' },
        RenderSkidoo: { Address: "0x6d010", Params: ['pointer'], Return: 'void' },
        RenderBoat: { Address: "0x16930", Params: ['pointer'], Return: 'void' },
        RoomChange: { Address: "0x3c9b0", Params: ['int', 'int'], Return: 'void' },
        GetRelYawPitch: { Address: "0x98340", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x7f750", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeH: { Address: "0x7f390", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeV: { Address: "0x7efd0", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x49da0", Params: ['pointer'], Return: 'void' },
        OnDamage: { Address: "0x763e0", Params: ['pointer', 'int', 'int'], Return: 'void' },
        AttachLaraHair: { Address: "0x7c430", Params: ['int', 'int'], Return: 'void' },
        ProcessGrenade: { Address: "0x454c0", Params: ['int16'], Return: 'void' },
        ProcessHarpoon: { Address: "0x45000", Params: ['int16'], Return: 'void' },
        ModernGfx: { Address: "0x20870", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        OgGfxPrep: { Address: "0x3cb20", Params: ['int'], Return: 'uint64' },
        RemoveEntity: { Address: "0x3c370", Params: ['int'], Return: 'void' },
        GetEntityBox: { Address: "0x7b930", Params: ['pointer'], Return: 'pointer' },
        RecordWorldState: { Address: "0x61700", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x62020", Params: ['int'], Return: 'void' },
        WorldStateRecordReplay: { Address: "0x79c80", Params: [], Return: 'void' },
        GetSector: { Address: "0xdb10", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        CalculateFloorHeight: { Address: "0xdf20", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CalculateCeilingHeight: { Address: "0xf160", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CanInterpolateCamera: { Address: "0x98080", Params: [], Return: 'int' },
    }
};
