/** tomb3.dll - Patch 4 */
module.exports = {
    variables: {
        BinaryTick: { Address: "0x18a504", Type: "Int8" },
        LevelCompleted: { Address: "0x18A4E8", Type: "Int32" },
        LevelId: { Address: "0x189fcc", Type: "Int32" },
        MenuSelection: { Address: "0x1640b4", Type: "UInt16" },
        MenuState: { Address: "0x55de22", Type: "UInt16" },
        WorldStateBackupPointer: { Address: "0x559c00", Type: "Block", Size: "0x3800" },
        ActionKeys: { Address: "0x45ca90", Type: "UInt32" },
        InterpolationFactor: { Address: "0x32b0bc", Type: "UInt32" },
        NewGamePlus: { Address: "0x55a4d4", Type: "UInt8" },
        LaraId: { Address: "0x39dce0", Type: "Int16" },
        Lara: { Address: "0x39de90", Type: "Pointer" },
        LaraOxygen: { Address: "0x39DCF6", Type: "Int16" },
        LaraCircleShadow: { Address: "0x39de90", Type: "Block", Pointer: "0xe20", Size: "0x30" },
        LaraClimbState: { Address: "0x39DCEE", Type: "Int16" },
        LaraBehaviourFlags: { Address: "0x39DD1C", Type: "Int8" },
        LaraGunFlags: { Address: "0x39dd20", Type: "UInt16" },
        LaraGunType: { Address: "0x39DCE4", Type: "Int32" },
        LaraAimingEnemy: { Address: "0x39ddd0", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x39ddd8", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x39ddda", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x39ddfc", Type: "Int16" },
        LaraAimingRight: { Address: "0x39de14", Type: "Int16" },
        RoomType: { Address: "0x39DCEC", Type: "Int16" },
        LaraHairLeftX: { Address: "0x3d8480", Type: "Int32" },
        UiTextsCount: { Address: "0x18FE08", Type: "Int16" },
        UiDrawX: { Address: "0x32b078", Type: "Int32" },
        UiDrawWidth: { Address: "0x32b07c", Type: "Int32" },
        UiDrawHeight: { Address: "0x32B0F0", Type: "Int32" },
        UiResWidth: { Address: "0x32B0E0", Type: "Int32" },
        UiResHeight: { Address: "0x32B0E4", Type: "Int32" },
        CameraStableX: { Address: "0x32b12c", Type: "Int32" },
        CameraStableY: { Address: "0x32b13c", Type: "Int32" },
        CameraStableZ: { Address: "0x32b14c", Type: "Int32" },
        CameraX: { Address: "0x32a8cc", Type: "Int32" },
        CameraY: { Address: "0x32a8dc", Type: "Int32" },
        CameraZ: { Address: "0x32a8ec", Type: "Int32" },
        CameraYaw: { Address: "0x32b10e", Type: "UInt16" },
        CameraPitch: { Address: "0x32b10c", Type: "UInt16" },
        CameraRightX: { Address: "0x32b120", Type: "Int32" },
        CameraRightY: { Address: "0x32b124", Type: "Int32" },
        CameraRightZ: { Address: "0x32b128", Type: "Int32" },
        CameraUpX: { Address: "0x32b130", Type: "Int32" },
        CameraUpY: { Address: "0x32b134", Type: "Int32" },
        CameraUpZ: { Address: "0x32b138", Type: "Int32" },
        CameraForwardX: { Address: "0x32b140", Type: "Int32" },
        CameraForwardY: { Address: "0x32b144", Type: "Int32" },
        CameraForwardZ: { Address: "0x32b148", Type: "Int32" },
        CameraFov: { Address: "0x32B0E8", Type: "Int32" },
        IsInGameScene: { Address: "0x16404C", Type: "Int32" },
        VehicleId: { Address: "0x39DD08", Type: "Int16" },
        Entities: { Address: "0x486f68", Type: "Pointer" },
        EntitiesCount: { Address: "0x45BD10", Type: "Int16" },
        Rooms: { Address: "0x45cb40", Type: "Pointer" },
        RoomsCount: { Address: "0x456C70", Type: "Int16" },
    },

    hooks: {
        RenderLara: { Address: "0x298b0", Params: ['pointer'], Return: 'void' },
        UpdateLaraAppearance: { Address: "0xf82e0", Params: [], Return: 'void' },
        CalculateLighting: { Address: "0xd59c0", Params: ['int', 'int', 'int', 'int', 'pointer'], Return: 'void' },
        LoadLevel: { Address: "0x3b1e0", Params: ['int', 'int', 'pointer', 'pointer'], Return: 'pointer' },
        InitializeLevelAI: { Address: "0x74cb0", Params: ['int'], Return: 'void' },
        SoundEffect: { Address: "0xe3f50", Params: ['int', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0x483a0", Params: [], Return: 'void' },
        Menu: { Address: "0x4aef0", Params: ['int'], Return: 'int' },
        Clone: { Address: "0x10d630", Params: ['pointer', 'pointer', 'uint64'], Return: 'pointer' },
        AddText: { Address: "0xfad80", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        DrawSetup: { Address: "0xc8480", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0xc9350", Params: ['int', 'int', 'int', 'int', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0xc9250", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        DrawHealth: { Address: "0xe0400", Params: ['int'], Return: 'void' },
        RoomChange: { Address: "0x516a0", Params: ['int', 'int'], Return: 'void' },
        RenderEntity: { Address: "0x29350", Params: ['pointer'], Return: 'void' },
        CalculateYawPitch: { Address: "0xe5460", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        TraceLineOfSight: { Address: "0xc7c00", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeX: { Address: "0xc7840", Params: ['pointer', 'pointer'], Return: 'int' },
        TraceRangeZ: { Address: "0xc7480", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x67ad0", Params: ['pointer'], Return: 'void' },
        OnDamage: { Address: "0xbbdd0", Params: ['pointer', 'int', 'int'], Return: 'void' },
        SimulateLaraHair: { Address: "0xc46b0", Params: ['int', 'int'], Return: 'void' },
        EntityGrenade: { Address: "0x62890", Params: ['int16'], Return: 'void' },
        ProcessRocket: { Address: "0x61750", Params: ['int16'], Return: 'void' },
        EntityHarpoon: { Address: "0x60b40", Params: ['int16'], Return: 'void' },
        CreateGraphic: { Address: "0x30540", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        RemoveEntity: { Address: "0x51040", Params: ['int'], Return: 'void' },
        GetEntityBox: { Address: "0xc3bb0", Params: ['pointer'], Return: 'pointer' },
        RecordWorldState: { Address: "0x9c340", Params: ['int'], Return: 'void' },
        RestoreWorldState: { Address: "0x9ce10", Params: ['int'], Return: 'void' },
        ProcessDemo: { Address: "0xc1ed0", Params: [], Return: 'void' },
        GetSector: { Address: "0x21d30", Params: ['int', 'int', 'int', 'pointer'], Return: 'pointer' },
        CalculateFloorHeight: { Address: "0x22210", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CalculateCeilingHeight: { Address: "0x235f0", Params: ['pointer', 'int', 'int', 'int'], Return: 'int' },
        CanInterpolateCamera: { Address: "0xe51a0", Params: [], Return: 'int' },
    }
};
