/** tomb5.dll - Patch 2 */
module.exports = {
    variables: {
        OutfitsLaraHairYoung: { Address: "0x1b5720", Type: "UInt64" },
        OutfitsLaraHairOld: { Address: "0x1b5780", Type: "UInt64" },
        OutfitsLaraSomeBasePointer: { Address: "0x6b2d60", Type: "UInt64" },
        OutfitsPointer: { Address: "0x128380", Type: "UInt64" },
        FacesPointer: { Address: "0x1288f0", Type: "UInt64" },
        BinaryTick: { Address: "0x1b6b88", Type: "Int8" },
        LevelChange: { Address: "0x65aad0", Type: "Int32" },
        ReturnToMainMenu: { Address: "0x1b6b2c", Type: "Int8" },
        NewGamePlus: { Address: "0x65ebb8", Type: "UInt8" },
        InterpolationFactor: { Address: "0x4ef8c8", Type: "UInt32" },
        LaraId: { Address: "0x4ee680", Type: "Int16" },
        Lara: { Address: "0x4ee840", Type: "Pointer" },
        LaraOxygen: { Address: "0x4ee696", Type: "Int16" },
        LaraPoisoned: { Address: "0x4ee6b2", Type: "Int16" },
        PoisonFactor: { Address: "0x1b6b58", Type: "Int16" },
        Rooms: { Address: "0x65eb68", Type: "Pointer" },
        RoomsCount: { Address: "0x65b230", Type: "Int16" },
        LaraCircleShadow: { Address: "0x1b2c20", Type: "Block", Pointer: "0x0", Size: "0xc" },
        LaraClimbState: { Address: "0x4ee68e", Type: "Int16" },
        LaraBehaviourFlags: { Address: "0x4ee6c4", Type: "Int8" },
        LaraHairLeftX: { Address: "0x4f3960", Type: "Int32" },
        LaraHairRightX: { Address: "0x4F400C", Type: "Int32" },
        LaraGunFlagsLeft: { Address: "0x4ee784", Type: "Int16" },
        LaraGunFlagsRight: { Address: "0x4ee79c", Type: "Int16" },
        LaraGunType: { Address: "0x4ee684", Type: "Int16" },
        LaraAimingEnemy: { Address: "0x4ee750", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x4ee758", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x4ee75a", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x4ee77c", Type: "Int16" },
        LaraScopeActive: { Address: "0x1b6bd4", Type: "Int32" },
        LaraScopeYaw: { Address: "0x4ee760", Type: "Int16" },
        LaraScopePitch: { Address: "0x4ee762", Type: "Int16" },
        LaraAimingRight: { Address: "0x4ee794", Type: "Int16" },
        RoomType: { Address: "0x4ee68c", Type: "Int16" },
        UiDrawX: { Address: "0x4ef7d0", Type: "Int32" },
        UiDrawWidth: { Address: "0x4ef7d4", Type: "Int32" },
        UiDrawHeight: { Address: "0x4ef7f4", Type: "Int32" },
        UiResWidth: { Address: "0x4ef818", Type: "Int32" },
        UiResHeight: { Address: "0x4ef81c", Type: "Int32" },
        CameraStableX: { Address: "0x4ef88c", Type: "Int32" },
        CameraStableY: { Address: "0x4ef89c", Type: "Int32" },
        CameraStableZ: { Address: "0x4ef8ac", Type: "Int32" },
        CameraX: { Address: "0x1b2ad0", Type: "Int32", Pointer: "0xc" },
        CameraY: { Address: "0x1b2ad0", Type: "Int32", Pointer: "0x10" },
        CameraZ: { Address: "0x1b2ad0", Type: "Int32", Pointer: "0x14" },
        CameraYaw: { Address: "0x4ef7ee", Type: "UInt16" },
        CameraPitch: { Address: "0x4ef7ec", Type: "UInt16" },
        CameraRightX: { Address: "0x4ef880", Type: "Int32" },
        CameraRightY: { Address: "0x4ef884", Type: "Int32" },
        CameraRightZ: { Address: "0x4ef888", Type: "Int32" },
        CameraUpX: { Address: "0x4ef890", Type: "Int32" },
        CameraUpY: { Address: "0x4ef894", Type: "Int32" },
        CameraUpZ: { Address: "0x4ef898", Type: "Int32" },
        CameraForwardX: { Address: "0x4EF8A0", Type: "Int32" },
        CameraForwardY: { Address: "0x4EF8A4", Type: "Int32" },
        CameraForwardZ: { Address: "0x4EF8A8", Type: "Int32" },
        CameraFov: { Address: "0x4ef820", Type: "Int32" },
        Entities: { Address: "0x66d0e8", Type: "Pointer" },
        EntitiesCount: { Address: "0x65b234", Type: "Int16" },
        Guns: { Address: "0x1b1f70", Type: "Int8" },
    },

    hooks: {
        RenderLara: { Address: "0x30830", Params: ['pointer'], Return: 'void' },
        ApplySettings: { Address: "0xf0c30", Params: ['pointer', 'pointer'], Return: 'void' },
        LoadedLevel: { Address: "0xfc350", Params: ['pointer'], Return: 'void' },
        InitializeLevelAI: { Address: "0x84d70", Params: ['int'], Return: 'void' },
        SoundEffect: { Address: "0xa43c0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        ProcessFreeaim: { Address: "0x133a0", Params: ['pointer', 'pointer', 'int', 'int'], Return: 'void' },
        DetectHit: { Address: "0xa0150", Params: ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0xe48c0", Params: [], Return: 'void' },
        Clone: { Address: "0x11cd20", Params: ['pointer', 'pointer', 'uint64'], Return: 'void' },
        RenderText: { Address: "0xe4700", Params: ['int', 'int', 'int', 'pointer', 'int'], Return: 'pointer' },
        DrawSetup: { Address: "0xa54c0", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0xa5fe0", Params: ['float', 'float', 'float', 'float', 'uint64', 'uint64'], Return: 'void' },
        DrawQuad: { Address: "0xa5f30", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int', 'float', 'float', 'float', 'float', 'int'], Return: 'void' },
        RoomChange: { Address: "0x46560", Params: ['int', 'int'], Return: 'void' },
        RenderEntity: { Address: "0x31680", Params: ['pointer'], Return: 'void' },
        GetRelYawPitch: { Address: "0xa1e60", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x12d50", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeH: { Address: "0x12990", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeV: { Address: "0x125d0", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x5beb0", Params: ['pointer'], Return: 'void' },
        OnDamage: { Address: "0x5c810", Params: ['pointer', 'int', 'int', 'int'], Return: 'void' },
        ModernGfx: { Address: "0x339b0", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        GetEntityBox: { Address: "0x9c710", Params: ['pointer'], Return: 'pointer' },
        RemoveEntity: { Address: "0x45fa0", Params: ['int'], Return: 'void' },
        AttachLaraHair: { Address: "0xedca0", Params: ['int', 'int'], Return: 'void' },
        ResetLaraHair: { Address: "0xed4a0", Params: [], Return: 'void' },
    }
};
