/** tomb4.dll - Patch 2 */
module.exports = {
    variables: {
        OutfitsLaraHairYoung: { Address: "0x1bad70", Type: "UInt64" },
        OutfitsLaraHairOld: { Address: "0x1badd0", Type: "UInt64" },
        OutfitsLaraSomeBasePointer: { Address: "0x6b6860", Type: "UInt64" },
        OutfitsPointer: { Address: "0x12c880", Type: "UInt64" },
        FacesPointer: { Address: "0x12cdc0", Type: "UInt64" },
        BinaryTick: { Address: "0x1bc144", Type: "Int8" },
        LevelChange: { Address: "0x661004", Type: "Int32" },
        ReturnToMainMenu: { Address: "0x1bc0f0", Type: "Int8" },
        NewGamePlus: { Address: "0x68f178", Type: "UInt8" },
        InterpolationFactor: { Address: "0x4957b0", Type: "UInt32" },
        LaraId: { Address: "0x4f3d80", Type: "Int16" },
        LaraBase: { Address: "0x4f3f40", Type: "UInt64" },
        LaraOxygen: { Address: "0x4f3d96", Type: "Int16" },
        LaraPoisoned: { Address: "0x4f3db2", Type: "Int16" },
        PoisonFactor: { Address: "0x1bc0c8", Type: "Int16" },
        Rooms: { Address: "0x664f08", Type: "Pointer" },
        RoomsCount: { Address: "0x661750", Type: "Int16" },
        LaraCircleShadow: { Address: "0x1b8cd0", Type: "Block", Pointer: "0x0", Size: "0xc" },
        LaraClimbState: { Address: "0x4f3d8e", Type: "Int16" },
        LaraBehaviourFlags: { Address: "0x4f3dc4", Type: "Int8" },
        LaraHairLeftX: { Address: "0x63eda0", Type: "Int32" },
        LaraHairRightX: { Address: "0x63F44C", Type: "Int32" },
        LaraGunFlagsLeft: { Address: "0x4f3e84", Type: "Int16" },
        LaraGunFlagsRight: { Address: "0x4f3e9c", Type: "Int16" },
        LaraGunType: { Address: "0x4f3d84", Type: "Int16" },
        LaraAimingEnemy: { Address: "0x4f3e50", Type: "UInt64" },
        LaraAimingYaw: { Address: "0x4f3e58", Type: "UInt16" },
        LaraAimingPitch: { Address: "0x4f3e5a", Type: "UInt16" },
        LaraAimingLeft: { Address: "0x4f3e7c", Type: "Int16" },
        LaraScopeActive: { Address: "0x1bc188", Type: "Int32" },
        LaraScopeYaw: { Address: "0x4f3e60", Type: "Int16" },
        LaraScopePitch: { Address: "0x4f3e62", Type: "Int16" },
        LaraAimingRight: { Address: "0x4f3e94", Type: "Int16" },
        RoomType: { Address: "0x4f3d8c", Type: "Int16" },
        UiDrawX: { Address: "0x49569c", Type: "Int32" },
        UiDrawWidth: { Address: "0x4956fc", Type: "Int32" },
        UiDrawHeight: { Address: "0x495700", Type: "Int32" },
        UiResWidth: { Address: "0x49571c", Type: "Int32" },
        UiResHeight: { Address: "0x495720", Type: "Int32" },
        CameraStableX: { Address: "0x49578c", Type: "Int32" },
        CameraStableY: { Address: "0x49579c", Type: "Int32" },
        CameraStableZ: { Address: "0x4957ac", Type: "Int32" },
        CameraX: { Address: "0x1b7d10", Type: "Int32", Pointer: "0xc" },
        CameraY: { Address: "0x1b7d10", Type: "Int32", Pointer: "0x10" },
        CameraZ: { Address: "0x1b7d10", Type: "Int32", Pointer: "0x14" },
        CameraYaw: { Address: "0x4956ee", Type: "UInt16" },
        CameraPitch: { Address: "0x4956ec", Type: "UInt16" },
        CameraRightX: { Address: "0x495780", Type: "Int32" },
        CameraRightY: { Address: "0x495784", Type: "Int32" },
        CameraRightZ: { Address: "0x495788", Type: "Int32" },
        CameraUpX: { Address: "0x495790", Type: "Int32" },
        CameraUpY: { Address: "0x495794", Type: "Int32" },
        CameraUpZ: { Address: "0x495798", Type: "Int32" },
        CameraForwardX: { Address: "0x4957A0", Type: "Int32" },
        CameraForwardY: { Address: "0x4957A4", Type: "Int32" },
        CameraForwardZ: { Address: "0x4957A8", Type: "Int32" },
        CameraFov: { Address: "0x495724", Type: "Int32" },
        VehicleId: { Address: "0x4f3da6", Type: "Int16" },
        Entities: { Address: "0x69abe0", Type: "Pointer" },
        EntitiesCount: { Address: "0x661754", Type: "Int16" },
        Guns: { Address: "0x1b6d00", Type: "Int8" },
    },

    hooks: {
        RenderLara: { Address: "0x2f420", Params: ['pointer'], Return: 'void' },
        ApplySettings: { Address: "0xf35b0", Params: ['pointer', 'pointer'], Return: 'void' },
        LoadedLevel: { Address: "0x1005c0", Params: ['pointer'], Return: 'void' },
        LaraInLevel: { Address: "0x87e70", Params: ['int'], Return: 'void' },
        SoundEffect: { Address: "0xd43d0", Params: ['int', 'pointer', 'int'], Return: 'int' },
        ProcessGrenade: { Address: "0x56b20", Params: ['int16'], Return: 'void' },
        ProcessHarpoon: { Address: "0x582a0", Params: ['int16'], Return: 'void' },
        ProcessFreeaim: { Address: "0x15440", Params: ['pointer', 'pointer', 'int', 'int'], Return: 'void' },
        DetectHit: { Address: "0xa76d0", Params: ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'int'], Return: 'int' },
        RenderUI: { Address: "0xedd70", Params: [], Return: 'void' },
        Clone: { Address: "0x120ee0", Params: ['pointer', 'pointer', 'uint64'], Return: 'void' },
        RenderText: { Address: "0xedbb0", Params: ['int', 'int', 'int', 'pointer', 'int'], Return: 'pointer' },
        DrawSetup: { Address: "0xb2410", Params: ['int', 'pointer'], Return: 'void' },
        DrawRect: { Address: "0xb2f30", Params: ['float', 'float', 'float', 'float', 'uint64', 'uint64'], Return: 'void' },
        RoomChange: { Address: "0x407b0", Params: ['int', 'int'], Return: 'void' },
        RenderEntity: { Address: "0x2fda0", Params: ['pointer'], Return: 'void' },
        GetRelYawPitch: { Address: "0xd6540", Params: ['int', 'int', 'int', 'pointer'], Return: 'void' },
        GetLOS: { Address: "0x14e20", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeH: { Address: "0x14a60", Params: ['pointer', 'pointer'], Return: 'int' },
        GetRangeV: { Address: "0x146a0", Params: ['pointer', 'pointer'], Return: 'int' },
        CheckAim: { Address: "0x5db60", Params: ['pointer'], Return: 'void' },
        DealDmg: { Address: "0x9b190", Params: ['pointer', 'int', 'int'], Return: 'void' },
        ModernGfx: { Address: "0x32240", Params: ['int', 'int', 'int', 'int', 'int', 'int', 'int'], Return: 'void' },
        GetEntityBox: { Address: "0xa3d00", Params: ['pointer'], Return: 'pointer' },
        RemoveEntity: { Address: "0x40130", Params: ['int'], Return: 'void' },
        AttachLaraHair: { Address: "0xefdb0", Params: ['int', 'int'], Return: 'void' },
        ResetLaraHair: { Address: "0xef5b0", Params: [], Return: 'void' },
    }
};
