module.exports = {
    id: "trr-123",
    type: "game",
    name: "Tomb Raider Remastered I-III",
    executable: "tomb123.exe",
    modules: {
        "tomb1.dll": { id: "tr1", name: "Tomb Raider I" },
        "tomb2.dll": { id: "tr2", name: "Tomb Raider II" },
        "tomb3.dll": { id: "tr3", name: "Tomb Raider III" }
    },
    constants: {
        ROOM_SIZE: 0xa8,
        ROOM_ENTITY_HEAD: 0x60,
        ENTITY_SIZE: 0xE50,
        ENTITY_BONES_SIZE: 0x2e0,
        ENTITY_POS_SIZE: 0x10,
        ENTITY_POS_NO_ROT_SIZE: 0xc,
        LARA_HAIR_SIZE: 0x6ac,
        LARA_BASIC_SIZE: 0x28,
        LARA_SHADOW_SIZE: 0x30,
        LARA_APPEARANCE_SIZE: 0xd,
        LARA_GUNFLAG_SIZE: 0x4,
        AI_TRACKING_SIZE: 0x16,
        PROJECTILE_SIZE: 0x44,
        ENTITY_X: 0x58,
        ENTITY_Y: 0x5c,
        ENTITY_Z: 0x60,
        ENTITY_YAW: 0x66,
        ENTITY_PITCH: 0x68,
        ENTITY_ROLL: 0x6a,
        ENTITY_LAST_X: 0x6c,
        ENTITY_ROOM: 0x1c,
        ENTITY_NEXT_IN_ROOM: 0x1e,
        ENTITY_NEXT_ID: 0x20,
        ENTITY_HEALTH: 0x26,
        ENTITY_BOX_INDEX: 0x28,
        ENTITY_BONES: 0x820,
        ENTITY_LAST_BONES: 0x1f0,
        ENTITY_XZ_SPEED: 0x22,
        ENTITY_Y_SPEED: 0x24,
        ENTITY_CURRENT_STATE: 0x12,
        ENTITY_TARGET_STATE: 0x14,
        ENTITY_QUEUED_STATE: 0x16,
        ENTITY_ANIM_ID: 0x18,
        ENTITY_ANIM_FRAME: 0x1a,
        ENTITY_TIMER: 0x2a,
        ENTITY_FLAGS: 0x2c,
        ENTITY_BEHAVIOUR: 0x50,
        ENTITY_STATUS: 0x1e4,
        ENTITY_MODEL: 0x10,
        ENTITY_DROP_1: 0x3a,
        ENTITY_DROP_2: 0x3c,
        ENTITY_DROP_3: 0x3e,
        ENTITY_DROP_4: 0x40,
        ENTITY_PUSHBLOCK_BUSY: 0x3c,
    },
    patches: {
        "patch4": {
            name: "Patch 4",
            patch: "c3d2a0188ad359a243c270c759dff142a131f302fa634fca404482875970673d",
            memory: {
                "tomb123.exe": require("./patches/patch4/tomb123.exe"),
                "tomb1.dll": require("./patches/patch4/tomb1.dll"),
                "tomb2.dll": require("./patches/patch4/tomb2.dll"),
                "tomb3.dll": require("./patches/patch4/tomb3.dll"),
            }
        },
        "patch4.1": {
            name: "Patch 4.1",
            patch: "d732834ad9f092968167e1a4c71f8c6bdb59809cee617b213f4f31e788504858",
            memory: {
                "tomb123.exe": require("./patches/patch4.1/tomb123.exe"),
                "tomb1.dll": require("./patches/patch4.1/tomb1.dll"),
                "tomb2.dll": require("./patches/patch4.1/tomb2.dll"),
                "tomb3.dll": require("./patches/patch4.1/tomb3.dll"),
            }
        }
    },
    defaultPatch: "patch4.1"
};
